### ISSUE TITLE
Add reproducible example

### ISSUE THREAD

**Issue by JosiahParry** [myyrakle/axum_static#4]
As indicated by the existence of this crate, its really not all that simple to serve files from Axum. Your crate seems like it would do the trick but there isn't any documentation to work off of. 

Could you consider creating a reproducible example?

**Comment by myyrakle** [comment]
Oh, I'm sorry! I just saw the issue.
The related part is going on in #5 PR. Please wait a little bit.

**Comment by myyrakle** [comment]
The PR for adding example code has been merged.

I apologize for being late.

**Comment by JosiahParry** [comment]
You rock!!!!!
